### ISSUE TITLE
GUI fixes for release 0.1

### ISSUE THREAD

**Issue by etsardou** [stdr-simulator-ros-pkg/stdr_simulator#113]
Spree 1 :
- [x] Register in active robots topic after the map is fetched
- [x] Fullscreen
- [x] Grid toggle change
- [x] Adjust button not toggle
- [x] line 108 stdr_info_loader.cpp -> core dump
- [x] Robot tag in transparent must not be visible
- [x] Tabs in forms 
- [x] Fix main widget menu
- [x] Erase kinematic from robot creator
- [x] Erase not used tags in lasers & sonars in robot creator 
- [x] Auto size -> adjust size
- [x] In right click : Delete not first
- [x] GUI still crashes on robot delete

**Comment by etsardou** [comment]
Spree 1 ok : 1a4119f7ad4add71807daa284aeb31c09b872727

**Comment by czalidis** [comment]
stdr_simulator logo on taskbar?

**Comment by etsardou** [comment]
Merged with #106
