### ISSUE TITLE
Robot / Server fixes for Release 0.1

### ISSUE THREAD

**Issue by etsardou** [stdr-simulator-ros-pkg/stdr_simulator#114]
- [x] When many_robots.launch is launched, if gui is spawned after the ROS warns, the robots cannot read the tf (in slow PCs)
- [x] With just 2 robots nodelet takes 80 - 120 % CPU (is this logical?)
- [x] When spawned 20 robots with launch, only 12 exist

**Comment by czalidis** [comment]
Can not spawn multiple robots from launchers, need to use command line interface.
