### ISSUE TITLE
Robots should not be able to drive through walls

### ISSUE THREAD

**Issue by trainman419** [stdr-simulator-ros-pkg/stdr_simulator#121]
Currently, there does not appear to be collision-checking between the robot and the obstacles in the map. Using teleop, I can drive the simulated robot through the walls and off the map.

**Comment by czalidis** [comment]
Yes, it is a known issue (see #74). We plan to provide this feature in the next release. See [ros wiki page](http://wiki.ros.org/stdr_simulator#What_would_you_expect_to_work_and_it_doesn.27t) for what is not working yet.

**Comment by trainman419** [comment]
Hooray! I guess I missed that when I was looking through tickets.

Closing as duplicate.

**Comment by etsardou** [comment]
Nevertheless, thanx for the feedback !
