### ISSUE TITLE
GUI does not respect current robot angle when calls move action

### ISSUE THREAD

**Issue by czalidis** [stdr-simulator-ros-pkg/stdr_simulator#125]
Right now, when you move a robot from gui, the new pose has a default theta value of 0.

**Comment by athallas** [comment]
29d23438f8015016c1320b5f632d99bfa294ef7d

**Comment by athallas** [comment]
Issue reopened in commit 6eb7c68963db950f399f65f8083f84fec7130b0c

**Comment by czalidis** [comment]
This issue needs to addressed in gui.
