### ISSUE TITLE
Problem with QT version on ubuntu  raring

### ISSUE THREAD

**Issue by jonbinney** [stdr-simulator-ros-pkg/stdr_simulator#128]
Compiles on raring but you have to run 
`catkin_make -DQT_QMAKE_EXECUTABLE=/usr/bin/qmake-qt4`
Not sure if there's an easy way to detect and set this variable in the CMakelists.txt

**Comment by jonbinney** [comment]
This might only be a problem if QT5 is also installed (it seems to automatically get set as the default once it is installed on raring)

**Comment by jonbinney** [comment]
Here is the relevant output of catkin_make:

```
-- +++ processing catkin package: 'stdr_gui'
-- ==> add_subdirectory(stdr_simulator/stdr_gui)
-- Looking for Q_WS_X11
-- Looking for Q_WS_X11 - not found
-- Looking for Q_WS_WIN
-- Looking for Q_WS_WIN - not found
-- Looking for Q_WS_QWS
-- Looking for Q_WS_QWS - not found
-- Looking for Q_WS_MAC
-- Looking for Q_WS_MAC - not found
CMake Error at /usr/share/cmake-2.8/Modules/FindQt4.cmake:1216 (message):
  Found unsuitable Qt version "5.0.1" from /usr/bin/qmake, this code requires
  Qt 4.x
Call Stack (most recent call first):
  stdr_simulator/stdr_gui/CMakeLists.txt:23 (find_package)


-- Configuring incomplete, errors occurred!
Invoking "cmake" failed
```

**Comment by czalidis** [comment]
Yes, the issue you mentioned appears when you have set Qt5 as default. I will try to find an elegant way to fix this in `CMakeLists.txt`. I am not sure if this is a bug that has to be addressed, though. If you have any ideas, on how to check and find the correct version of Qt, I'll be happy to review a pull request.

**Comment by jonbinney** [comment]
Yeah, it isn't a huge problem, but it could be annoying for new users who don't know why it isn't compiling.  I've submitted a PR that works around the problem by setting an environment variable in the CMakeLists.txt that forces qt4 instead of qt5.

**Comment by czalidis** [comment]
If I understand well there is a tool available, [qtchooser](http://manpages.ubuntu.com/manpages/saucy/man1/qtchooser.1.html), to select between qt versions.

@jonbinney can you give it a try and give me feedback on how to use it, to update [this](http://wiki.ros.org/stdr_simulator/Tutorials/Set%20up%20STDR%20Simulator) tutorial page. 

EDIT: `qtchooser` uses the environment variable `QT_SELECT` to select the version, so this is similar to the PR you proposed.

**Comment by jonbinney** [comment]
Yeah - qtchooser has a bug in raring: https://bugs.launchpad.net/ubuntu/+source/qtchooser/+bug/1155861

To work around that, you have to do `sudo apt-get install qt4-default`
