### ISSUE TITLE
parent of /robot0/laser_0 cannot be found

### ISSUE THREAD

**Issue by galou** [stdr-simulator-ros-pkg/stdr_simulator#163]
I launch "roslaunch stdr_launchers server_with_map_and_gui_plus_robot.launch".

The `header.frame_id` of message in topic `/robot0/laser_0` is set to `"/robot0_laser_0"`.
However, the tf frame is `"robot0_laser_0"`, without "/".

This is a problem for `tf::TransformListener::getParent`.
`tf_listerner.getParent(scan.header.frame_id, ros::Time(0), parent)` --> returns `false`
`tf_listerner.getParent("robot0_laser_0", ros::Time(0), parent)` --> returns `true`

I guess this is a problem for other messages as well.

**Comment by czalidis** [comment]
Ok, I confirm the problem. 

@galou Does this issue affects anything else besides `tf::TransformListener::getParent`?

As I can see, everything else seems to work. You can see below the tf tree that corresponds to the launcher you are mentioning. Seems ok to me. Doesn't `rqt_tf_tree` use `tf::TransformListener::getParent` to find parent frames?
![stdr_frames](https://cloud.githubusercontent.com/assets/1313541/4938254/15f6218a-65ca-11e4-91f7-41f1b22e4d39.png)

**Comment by galou** [comment]
I had a look at the source code of `tf.waitForTransform` calls `"strip_leading_slash(target_frame)"`whereas `getParent` doesn't. I filed an issue on tf: https://github.com/ros/geometry/issues/74.

I don't know what is the best practice for tf frame names, with or without leading '/'.

**Comment by galou** [comment]
The leading slash also affects `tf::TransformListener::frameExists`.

I wrote PR #168 for review.

**Comment by czalidis** [comment]
Closed via 6307d18cc7eb4b3a92939eb71cf1f174bc0479ff
