### ISSUE TITLE
Bug with footprint loading

### ISSUE THREAD

**Issue by etsardou** [stdr-simulator-ros-pkg/stdr_simulator#171]
When a robot is loaded (either added in the map or loaded in the robot creator) the footprint is uninitialized. Probably a bug in the parser.

**Comment by etsardou** [comment]
Actually many elements are not loaded correctly.

Notes:
- Affects both xml and yaml files
- OS: Ubuntu 14.04, ROS Indigo
- yaml-cpp: 0.5.1
- The robot_msgs is wrong in the parser msg creation
- stdr_yaml_parser seems to create the correct Node\* structure with the correct values

**Comment by etsardou** [comment]
Check the code in the `kinematic_models_support` branch. To reproduce:
- launch the `roslaunch stdr_launchers server_with_map_and_gui_plus_robot.launch`
- The predefined robot is spawned correctly. ROS_ERROR messages are evident in the console. These exist here: https://github.com/stdr-simulator-ros-pkg/stdr_simulator/blob/motion_controllers_support/stdr_parser/src/stdr_parser_msg_creator.cpp#L168
- Try to add a new predefined robot (e.g. pandora.yaml which is the one loaded in the previous launcher). The string in the yaml and the Node\* structure is correct but the `atof` seems to fail (https://github.com/stdr-simulator-ros-pkg/stdr_simulator/blob/motion_controllers_support/stdr_parser/src/stdr_parser_msg_creator.cpp#L194).

**Comment by oscar-lima** [comment]
when launching :

roslaunch stdr_launchers server_with_map_and_gui_plus_robot.launch

in branch : motion_controllers_support

i get this errors in console:

[ERROR] [/robot_spawn_oscar_MacBook_11898_4164890650817676037]: Footprint_specifications found
[ERROR] [/robot_spawn_oscar_MacBook_11898_4164890650817676037]: The value is: 0.200000002980232
[ERROR] [/robot_spawn_oscar_MacBook_11898_4164890650817676037]: 0.2
[ERROR] [/robot_spawn_oscar_MacBook_11898_4164890650817676037]: The radius is 0.200000

but the robot seems to be working fine.

**Comment by etsardou** [comment]
Ok great, thank you :)
