### ISSUE TITLE
Inidigo version missing dependency on map_server

### ISSUE THREAD

**Issue by trainman419** [stdr-simulator-ros-pkg/stdr_simulator#172]
The released version of stdr_server in Indigo is missing a runtime dependency on map_server.

This means that map_server is not installed when installing stdr_server from debs, and it results in an error when trying to start stdr_server_node:

```
/opt/ros/indigo/lib/stdr_server/stdr_server_node: error while loading shared libraries: libimage_loader.so: cannot open shared object file: No such file or directory
```

**Comment by czalidis** [comment]
Thanks Austin, it's obviously a mistake. I don't know why it is listed only as a `build_depend`. I will fix it, but it might take some time until the next binary release.

**Comment by trainman419** [comment]
Thanks!
