### ISSUE TITLE
robot spawn crashes when loading yaml omni robot

### ISSUE THREAD

**Issue by oscar-lima** [stdr-simulator-ros-pkg/stdr_simulator#175]
it is able to load xml robots but when loading yaml robot in the same format gives this error:

[ERROR] [1443388603.185013601]: [STDR_PARSER] STDR parser : kinematic_specificacions is not allowed in a kinematic tag
Trail: 
  [kinematic_specificacions] Line 36 of file 'cob3-1.yaml'
  [robot_specifications] Line 0 of file 'cob3-1.yaml'
  [robot] Line -1 of file 'cob3-1.yaml'

this is my yaml configuration file:

https://github.com/oscar-lima/cob3_navigation_sim/blob/hydro/ros/config/cob3-1.yaml

and this is the xml configuration file:

https://github.com/oscar-lima/cob3_navigation_sim/blob/hydro/ros/config/cob3-1.xml

other related launch files, etc can be consulted in the repository:

https://github.com/oscar-lima/cob3_navigation_sim

**Comment by etsardou** [comment]
Hi Oscar, I believe you have misspelled "specifications". Please check again with the proper tag `kinematic_specifications`.

**Comment by etsardou** [comment]
And just a question: Does that bug occurs to you too? https://github.com/stdr-simulator-ros-pkg/stdr_simulator/issues/171

Thnx

**Comment by oscar-lima** [comment]
Your are correct, it was a miss spelling error, i commented on issue 171 already. This issue can be then closed now

**Comment by oscar-lima** [comment]
just as a comment, when launching the yaml robot in:

https://github.com/oscar-lima/cob3_navigation_sim/blob/hydro/ros/config/cob3-1.yaml

I get this errors:

[ERROR] [/robot_spawn_oscar_MacBook_12590_2934590099813672843]: Footprint_specifications found
[ERROR] [/robot_spawn_oscar_MacBook_12590_2934590099813672843]: The value is: 0.5
[ERROR] [/robot_spawn_oscar_MacBook_12590_2934590099813672843]: 0.5
[ERROR] [/robot_spawn_oscar_MacBook_12590_2934590099813672843]: The radius is 0.500000

although the robot works fine.

I guess this was your question regarding issue 171.
