### ISSUE TITLE
Write yaml parser

### ISSUE THREAD

**Issue by etsardou** [stdr-simulator-ros-pkg/stdr_simulator#23]
Yaml 2 RobotMsg and 
RobotMsg 2 Yaml

**Comment by czalidis** [comment]
c3628bfd4e3c76280b584132d4897bbd20d6d476 Simple parser complete. Need to add Sensor 2 Yaml and Yaml to sensor. Almost ready.

**Comment by etsardou** [comment]
84b242b423ff0189cfb0cd786f7ea1aea756db82
