### ISSUE TITLE
Load map from GUI and send it to Server

### ISSUE THREAD

**Issue by etsardou** [stdr-simulator-ros-pkg/stdr_simulator#24]

**Comment by czalidis** [comment]
This functionality is implemented on the server side. We use the external library `image_loader` of ros package `map_server`. We should change the server's interface to load maps directly from `nav_msgs::OccupancyGrid` and move image loading functionality to an other library, that can be implemented either from a Gui or a node that takes the map file as command line argument. With that approach map is no longer depended on local map files.

**Comment by czalidis** [comment]
server side implementation done
