### ISSUE TITLE
collision checking not working

### ISSUE THREAD

**Issue by etsardou** [stdr-simulator-ros-pkg/stdr_simulator#74]

**Comment by etsardou** [comment]
Almost working. There are still bugs. To reproduce run 

roslaunch stdr_launchers server_with_map_and_gui_plus_robot.launch

and then

rostopic pub /robot0/cmd_vel geometry_msgs/Twist -r 10000 '[0.5, 0, 0]' '[0, 0, 0.1]'
rostopic pub /robot0/cmd_vel geometry_msgs/Twist -r 10000 '[-0.5, 0, 0]' '[0, 0, 0.1]'
rostopic pub /robot0/cmd_vel geometry_msgs/Twist -r 10000 '[0.5, 0, 0]' '[0, 0, 0.1]'

Then the robot is stuck

**Comment by etsardou** [comment]
14fc5d611807f9e1f887195e129f6717938d9016

**Comment by czalidis** [comment]
When moving the robot from gui, you can move it on top of an obstacle. Needs to detect collision and not allow movement.

**Comment by etsardou** [comment]
b153373f325491980c985cad72ec1e77dcdec471
