### ISSUE TITLE
Gui has to calculate poses in respect to map origin

### ISSUE THREAD

**Issue by czalidis** [stdr-simulator-ros-pkg/stdr_simulator#85]

**Comment by etsardou** [comment]
For some reason this works without changes. Maybe robot doesn't take into consideration the origin?

**Comment by czalidis** [comment]
You are right, server does not have a dynamic transform from `world` to `map`. It is statically connected with a `static_transform_publisher`. We can change that so map server publishes the transform (which is the correct solution) or leave it as is :).

**Comment by czalidis** [comment]
I will review the general concept of tf in the simulator because it is associated with #84.

**Comment by czalidis** [comment]
with new tf frame `map_static`, this is very simple, just refer to that frame and tf takes care of the transformations.

**Comment by czalidis** [comment]
aff29b6744f7f1c1b622d5ca7bd3f9935d6c7b6f
